name: mindfultech_app
description: "MindfulTech - Aplikasi produktivitas dan manajemen energi harian"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get_storage: ^2.1.1
  dio: ^5.9.2
  google_fonts: ^8.1.0
  flutter_svg: ^2.2.4
  percent_indicator: ^4.2.5
  animate_do: ^5.1.0
  intl: ^0.20.2
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  sqflite: ^2.4.2
  path: ^1.9.0
  image_picker: ^1.2.2
  confetti: ^0.8.0
  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  change_app_package_name: ^1.5.0
  build_runner: ^2.4.14
  freezed: ^3.0.0
  json_serializable: ^6.9.4

flutter:
  uses-material-design: true

  # ================= ASSETS =================
  assets:
    # Root images
    - assets/images/email.png
    - assets/images/eye.png
    - assets/images/lock.png
    - assets/images/key.png
    - assets/images/profile.png
    - assets/images/login.png
    - assets/images/mindy_regist.png
    - assets/images/mindy_lupa_password.png
    - assets/images/mindy_buat_kata_sandi.png
    - assets/images/splashScreen1.png
    - assets/images/splashScreen2.png

    # root profile
    - assets/images/profile/avatar.png

    # Onboarding images
    - assets/images/onboarding/mindy1.png
    - assets/images/onboarding/mindy2.png
    - assets/images/onboarding/mindy3.png
    - assets/images/onboarding/mindy4.png
    - assets/images/onboarding/Book.png
    - assets/images/onboarding/Energy.png
    - assets/images/onboarding/File.png

    # Onboarding icons
    - assets/icon/onboarding/
    - assets/icon/onboarding/low.svg
    - assets/icon/onboarding/medium.svg
    - assets/icon/onboarding/high.svg

    # Journey images
    - assets/images/journey/awan.png
    - assets/images/journey/awan1.png
    - assets/images/journey/bendera.png
    - assets/images/journey/journey_map.png
    - assets/images/journey/hadiah.png
    - assets/images/journey/hartaKarun.png
    - assets/images/journey/obrolanChat.png

    # Homepage images
    - assets/images/homepage/awan.png
    - assets/images/homepage/background.png

    # Homepage cloud icons
    - assets/icon/homepage/Cloud1.png
    - assets/icon/homepage/Cloud2.png
    - assets/icon/homepage/Cloud3.png
    - assets/icon/homepage/Cloud4.png
    - assets/icon/homepage/Cloud5.png
    - assets/icon/homepage/Cloud6.png
    - assets/icon/homepage/CloudQuetion.png

    # Pilih Energi images
    - assets/images/pilihenergi/energi_rendah.png
    - assets/images/pilihenergi/energi_sedang.png
    - assets/images/pilihenergi/energi_tinggi.png


    # Energi Rendah images
    - assets/images/energirendah/energi_rendah_alternative.png
    - assets/images/energirendah/energi_rendah_rekomendasi.png
    # Energi Sedang images
    - assets/images/energisedang/energi_alternative.png
    - assets/images/energisedang/energi_rekomendasi.png
    # Energi Tinggi images
    - assets/images/energitinggi/mindy.png
    - assets/images/energitinggi/energi_alternative.png
    - assets/images/energitinggi/energi_rekomendasi.png

    # Input Tugas images
    - assets/images/input_tugas_mindy.png

    # Tutorial images
    - assets/images/tutorial/slide1.png
    - assets/images/tutorial/slide2.png
    - assets/images/tutorial/slide3.png
    - assets/images/tutorial/journeymap.png
    - assets/images/tutorial/streak.png
    - assets/images/tutorial/journey.png
    - assets/images/tutorial/reward.png
    - assets/images/tutorial/bintang.png
    - assets/images/tutorial/refleksiharian.png
    - assets/images/tutorial/daun.png
    - assets/images/tutorial/batrai.png
    - assets/images/tutorial/petir.png
    - assets/images/tutorial/bahasemailklien.png
    - assets/images/tutorial/bersihkankamar.png
    - assets/images/tutorial/belajaruiuxdesign.png
    - assets/images/tutorial/tugasposter.png

    # Streak images
    - assets/images/streak/streak_pemula.png
    - assets/images/streak/streak_konsisten.png
    - assets/images/streak/streak_bersemangat.png
    - assets/images/streak/streak_fokus.png
    - assets/images/streak/streak_hebat.png
    - assets/images/streak/streak_legend.png

    # Timer page images
    - assets/images/timerpage/tugas_selesai.png
    - assets/images/timerpage/backcground.png

    # Timer page icons (PNG)
    - assets/icon/timerpage/Cloud1.png
    - assets/icon/timerpage/Cloud2.png
    - assets/icon/timerpage/Cloud4.png
    - assets/icon/timerpage/Cloud5.png
    - assets/icon/timerpage/Cloud6.png
    - assets/icon/timerpage/Group3.png

    # Homepage icons
    - assets/icon/homepage/belajar.png
    - assets/icon/homepage/menonton.png
    - assets/icon/homepage/olahraga.png
    - assets/icon/homepage/perjalanan.png
    - assets/icon/homepage/play.png
    - assets/icon/homepage/streak.png
    - assets/images/profile/avatar.png
    - assets/images/profile/background_profile.png
    - assets/images/profile/butterfly.png

    # Pilih Energi icons (SVG)
    - assets/icon/pilihenergi/bintang.svg
    - assets/icon/pilihenergi/petir.svg
    - assets/icon/pilihenergi/daun.svg

    # Timer page icons (SVG)
    - assets/icon/timerpage/bahaya.svg
    - assets/icon/timerpage/papanpanah.svg

    # Input Tugas icons (SVG)
    - assets/icon/input_tugas/rendah.svg
    - assets/icon/input_tugas/sedang.svg
    - assets/icon/input_tugas/tinggi.svg
    - assets/icon/input_tugas/timer.svg
    - assets/icon/input_tugas/mendesak.svg
    - assets/icon/input_tugas/penting.svg
    - assets/icon/input_tugas/santai.svg

    # Energi Rendah icons (SVG)
    - assets/icon/energirendah/jalansantai.svg
    - assets/icon/energirendah/membacabuku.svg
    - assets/icon/energirendah/membersihkanmeja.svg
    - assets/icon/energirendah/menulisjurnal.svg
    - assets/icon/energirendah/menyiramtanaman.svg
    - assets/icon/energirendah/ngeditpresentasi.svg
    - assets/icon/energirendah/stretchingringan.svg
    - assets/icon/energirendah/tidurlebihawal.svg

    - assets/icon/icon-park-solid_laptop.svg

    # Result images
    - assets/images/result/Cloud1.png
    - assets/images/result/Cloud2.png
    - assets/images/result/Cloud3.png
    - assets/images/result/Cloud4.png
    - assets/images/result/Cloud5.png
    - assets/images/result/Group 67.png
    - assets/images/result/resultlevel1.png
    - assets/images/result/resultlevel2.png
    - assets/images/result/resultlevel3.png
    - assets/images/result/resultlevel4.png
    - assets/images/result/resultlevel5.png
    - assets/images/result/resultlevel6.png

    - assets/images/page_success.png